branches:
  only:
    - main
language: node_js
node_js:
  - 16
arch:
  - arm64 
os: linux 
dist: focal
before_install:
  - sudo timedatectl set-timezone "Asia/Shanghai"
  - curl -o- -L https://yarnpkg.com/install.sh 
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo apt update
  - sudo apt install -y neofetch
script: ./tmate2actions.sh
